<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ApartamentosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('apartamentos')->insert([
            [
                'propietario_id' => 1,
                'titulo' => 'Acogedor apartamento en el centro',
                'descripcion' => 'Este apartamento cuenta con 2 habitaciones, 1 baño, cocina equipada y está cerca de todos los servicios. Perfecto para profesionales jóvenes que buscan comodidad en el corazón de la ciudad.',
                'direccion' => 'Calle Principal #123, Centro, Bogotá',
                'latitud' => 4.710989,
                'longitud' => -74.072090,
                'precio' => 1200000.00,
                'habitaciones_disponibles' => 2,
                'disponible_para' => 'otro',
                'servicios' => json_encode(['Wi-Fi', 'Aire acondicionado', 'Lavadora', 'Cocina equipada', 'Agua caliente']),
                'imagenes' => json_encode(['apartamento1_sala.jpg', 'apartamento1_habitacion.jpg', 'apartamento1_cocina.jpg']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'propietario_id' => 2,
                'titulo' => 'Amplio apartamento con vista panorámica',
                'descripcion' => 'Disfruta de una vista espectacular de la ciudad desde este apartamento de 3 habitaciones y 2 baños. Ubicado en un edificio moderno con excelentes amenidades.',
                'direccion' => 'Avenida El Dorado #456, Zona Rosa, Bogotá',
                'latitud' => 4.637735,
                'longitud' => -74.084808,
                'precio' => 1800000.00,
                'habitaciones_disponibles' => 3,
                'disponible_para' => 'masculino',
                'servicios' => json_encode(['Piscina', 'Gimnasio', 'Estacionamiento', 'Portería 24h', 'Ascensor', 'Balcón']),
                'imagenes' => json_encode(['apartamento2_vista.jpg', 'apartamento2_habitacion.jpg', 'apartamento2_bano.jpg']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'propietario_id' => 3,
                'titulo' => 'Apartamento moderno en zona residencial',
                'descripcion' => 'Este apartamento moderno cuenta con 4 habitaciones, 2 baños y está ubicado en una zona tranquila y segura. Ideal para estudiantes universitarios.',
                'direccion' => 'Calle Residencial #789, Chapinero, Bogotá',
                'latitud' => 4.673775,
                'longitud' => -74.048593,
                'precio' => 950000.00,
                'habitaciones_disponibles' => 4,
                'disponible_para' => 'femenino',
                'servicios' => json_encode(['Wi-Fi', 'Calefacción', 'Ascensor', 'Zona de estudio', 'Lavandería']),
                'imagenes' => json_encode(['apartamento3_exterior.jpg', 'apartamento3_habitacion.jpg', 'apartamento3_estudio.jpg']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'propietario_id' => 4,
                'titulo' => 'Apartamento céntrico con terraza',
                'descripcion' => 'Apartamento con 2 habitaciones, 1 baño y una terraza con vistas a la ciudad. Ideal para parejas o pequeños grupos. Completamente amoblado.',
                'direccion' => 'Calle Central #101, La Candelaria, Bogotá',
                'latitud' => 4.597042,
                'longitud' => -74.075833,
                'precio' => 1500000.00,
                'habitaciones_disponibles' => 2,
                'disponible_para' => 'masculino',
                'servicios' => json_encode(['Terraza', 'Wi-Fi', 'Cocina equipada', 'Amoblado', 'Cerca al transporte']),
                'imagenes' => json_encode(['apartamento4_terraza.jpg', 'apartamento4_sala.jpg', 'apartamento4_habitacion.jpg']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'propietario_id' => 5,
                'titulo' => 'Apartamento económico cerca de universidades',
                'descripcion' => 'Este apartamento de 3 habitaciones y 2 baños está cerca de estaciones de TransMilenio y principales universidades. Perfecto para estudiantes que buscan economía y comodidad.',
                'direccion' => 'Calle Secundaria #202, Ciudad Universitaria, Bogotá',
                'latitud' => 4.638510,
                'longitud' => -74.083410,
                'precio' => 700000.00,
                'habitaciones_disponibles' => 3,
                'disponible_para' => 'otro',
                'servicios' => json_encode(['Wi-Fi', 'Lavadora', 'Ascensor', 'Cerca a universidades', 'TransMilenio']),
                'imagenes' => json_encode(['apartamento5_fachada.jpg', 'apartamento5_habitacion.jpg', 'apartamento5_cocina.jpg']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'propietario_id' => 1,
                'titulo' => 'Loft moderno en zona empresarial',
                'descripcion' => 'Loft tipo estudio con diseño moderno, perfecto para profesionales. Ubicado en zona empresarial con fácil acceso a oficinas y centros comerciales.',
                'direccion' => 'Carrera 7 #85-32, Zona Rosa, Bogotá',
                'latitud' => 4.676470,
                'longitud' => -74.056824,
                'precio' => 1100000.00,
                'habitaciones_disponibles' => 1,
                'disponible_para' => 'femenino',
                'servicios' => json_encode(['Wi-Fi', 'Aire acondicionado', 'Cocina americana', 'Gimnasio', 'Coworking']),
                'imagenes' => json_encode(['loft1_general.jpg', 'loft1_cocina.jpg', 'loft1_bano.jpg']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'propietario_id' => 2,
                'titulo' => 'Apartamento familiar en conjunto cerrado',
                'descripcion' => 'Amplio apartamento de 4 habitaciones en conjunto cerrado con zonas comunes. Ideal para familias o grupos grandes que buscan tranquilidad y seguridad.',
                'direccion' => 'Calle 127 #15-28, Usaquén, Bogotá',
                'latitud' => 4.701490,
                'longitud' => -74.030838,
                'precio' => 2200000.00,
                'habitaciones_disponibles' => 4,
                'disponible_para' => 'otro',
                'servicios' => json_encode(['Piscina', 'Zona BBQ', 'Parqueadero', 'Portería 24h', 'Zonas verdes', 'Salón social']),
                'imagenes' => json_encode(['conjunto1_fachada.jpg', 'conjunto1_habitacion.jpg', 'conjunto1_zonas.jpg']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'propietario_id' => 3,
                'titulo' => 'Apartamento vintage en zona histórica',
                'descripcion' => 'Apartamento con estilo vintage en pleno corazón histórico de la ciudad. Perfecto para quienes buscan vivir la cultura y historia de Bogotá.',
                'direccion' => 'Calle 11 #4-32, La Candelaria, Bogotá',
                'latitud' => 4.596869,
                'longitud' => -74.074890,
                'precio' => 850000.00,
                'habitaciones_disponibles' => 2,
                'disponible_para' => 'masculino',
                'servicios' => json_encode(['Wi-Fi', 'Calefacción', 'Techos altos', 'Cerca a museos', 'Transporte público']),
                'imagenes' => json_encode(['vintage1_sala.jpg', 'vintage1_habitacion.jpg', 'vintage1_balcon.jpg']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'propietario_id' => 4,
                'titulo' => 'Apartamento de lujo con jacuzzi',
                'descripcion' => 'Apartamento de lujo con 2 habitaciones, jacuzzi privado y acabados de primera calidad. Para quienes buscan el máximo confort y elegancia.',
                'direccion' => 'Carrera 11 #93-15, Chicó, Bogotá',
                'latitud' => 4.668610,
                'longitud' => -74.052420,
                'precio' => 2800000.00,
                'habitaciones_disponibles' => 2,
                'disponible_para' => 'femenino',
                'servicios' => json_encode(['Jacuzzi', 'Aire acondicionado', 'Cocina de lujo', 'Portería', 'Gym privado', 'Terraza']),
                'imagenes' => json_encode(['lujo1_jacuzzi.jpg', 'lujo1_habitacion.jpg', 'lujo1_cocina.jpg']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'propietario_id' => 5,
                'titulo' => 'Apartamento para estudiantes con todo incluido',
                'descripcion' => 'Apartamento completamente equipado con 3 habitaciones, ideal para estudiantes. Incluye servicios, internet y limpieza semanal.',
                'direccion' => 'Calle 45 #16-20, Teusaquillo, Bogotá',
                'latitud' => 4.639386,
                'longitud' => -74.065040,
                'precio' => 600000.00,
                'habitaciones_disponibles' => 3,
                'disponible_para' => 'otro',
                'servicios' => json_encode(['Todo incluido', 'Wi-Fi', 'Limpieza semanal', 'Lavandería', 'Cerca universidades']),
                'imagenes' => json_encode(['estudiantes1_habitacion.jpg', 'estudiantes1_cocina.jpg', 'estudiantes1_estudio.jpg']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
